name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:     # Allows manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub contribution snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: sanjai-8-11
          outputs: |
            dist/github-contribution-grid-snake-default.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
